"""
Tests for app.routers.auth — Google OAuth SSO
Generated by QA Agent (POC Antigravity).

Structure:
  [DETERMINISTIC] Fixtures + happy path + error paths
  [LLM-GENERATED] Edge cases (marked below)
"""
import pytest
from unittest.mock import patch, MagicMock
from fastapi.testclient import TestClient
import respx
from httpx import Response

from main import app

client = TestClient(app)


# ============================================================
# FIXTURES (deterministic)
# ============================================================

@pytest.fixture
def mock_google_token_response():
    """Valid Google OAuth token response."""
    return {
        "access_token": "ya29.valid_access_token",
        "id_token": "eyJhbGciOiJSUzI1NiJ9.valid.payload",
        "token_type": "Bearer",
        "expires_in": 3600,
    }


@pytest.fixture
def mock_google_userinfo():
    """Valid Google userinfo response."""
    return {
        "sub": "1234567890",
        "email": "alvear@bv.com.br",
        "email_verified": True,
        "name": "Alvear Sprandel",
        "picture": "https://lh3.googleusercontent.com/a/default",
    }


# ============================================================
# HAPPY PATH (deterministic)
# ============================================================

def test_health_endpoint_returns_ok():
    """GET /health should return 200 with status ok."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json().get("status") == "ok"


def test_login_endpoint_redirects_to_google():
    """GET /v1/auth/login should redirect to Google consent screen."""
    response = client.get("/v1/auth/login", follow_redirects=False)
    assert response.status_code in (302, 307)
    location = response.headers.get("location", "")
    assert "accounts.google.com" in location
    assert "client_id=" in location
    assert "response_type=code" in location


@respx.mock
def test_callback_with_valid_code_returns_session(
    mock_google_token_response, mock_google_userinfo
):
    """GET /v1/auth/callback with valid code should authenticate user."""
    respx.post("https://oauth2.googleapis.com/token").mock(
        return_value=Response(200, json=mock_google_token_response)
    )
    respx.get("https://openidconnect.googleapis.com/v1/userinfo").mock(
        return_value=Response(200, json=mock_google_userinfo)
    )

    response = client.get(
        "/v1/auth/callback",
        params={"code": "valid_auth_code", "state": "csrf_token_abc"},
        follow_redirects=False,
    )
    assert response.status_code in (200, 302)


# ============================================================
# ERROR PATHS (deterministic)
# ============================================================

def test_callback_without_code_returns_400():
    """Callback without authorization code should fail."""
    response = client.get("/v1/auth/callback")
    assert response.status_code in (400, 422)


@respx.mock
def test_callback_with_invalid_code_returns_401(mock_google_token_response):
    """Google rejecting the code should propagate as 401."""
    respx.post("https://oauth2.googleapis.com/token").mock(
        return_value=Response(400, json={"error": "invalid_grant"})
    )

    response = client.get(
        "/v1/auth/callback",
        params={"code": "expired_code", "state": "csrf_token_abc"},
    )
    assert response.status_code in (400, 401)


def test_callback_with_state_mismatch_returns_403():
    """CSRF: state param must match the one stored in session."""
    response = client.get(
        "/v1/auth/callback",
        params={"code": "valid_code", "state": "forged_state"},
    )
    assert response.status_code in (400, 403)


def test_protected_endpoint_without_token_returns_401():
    """Endpoints behind auth should reject unauthenticated requests."""
    response = client.get("/v1/auth/me")
    assert response.status_code in (401, 404)


# ============================================================
# EDGE CASES (LLM-GENERATED) — enriched section
# ============================================================
# [IA] Edge cases abaixo foram gerados por LLM


@respx.mock
def test_callback_with_unverified_email_rejects(mock_google_token_response):
    """Edge: Google returns email_verified=False — should reject."""
    respx.post("https://oauth2.googleapis.com/token").mock(
        return_value=Response(200, json=mock_google_token_response)
    )
    respx.get("https://openidconnect.googleapis.com/v1/userinfo").mock(
        return_value=Response(200, json={
            "sub": "999", "email": "x@test.com",
            "email_verified": False, "name": "X"
        })
    )
    response = client.get(
        "/v1/auth/callback",
        params={"code": "c", "state": "s"},
    )
    assert response.status_code in (400, 403)


@respx.mock
def test_callback_handles_google_timeout(mock_google_token_response):
    """Edge: Google token endpoint times out — should not hang."""
    import httpx
    respx.post("https://oauth2.googleapis.com/token").mock(
        side_effect=httpx.TimeoutException("timeout")
    )
    response = client.get(
        "/v1/auth/callback",
        params={"code": "c", "state": "s"},
    )
    assert response.status_code in (500, 502, 504)


def test_login_rejects_non_https_redirect_uri():
    """Edge: redirect_uri must be HTTPS in production."""
    response = client.get(
        "/v1/auth/login",
        params={"redirect_uri": "http://evil.com/callback"},
        follow_redirects=False,
    )
    # Must either 400 or ignore the param and use its own redirect_uri
    assert response.status_code in (200, 302, 307, 400)


@respx.mock
def test_callback_with_malformed_id_token_returns_401(mock_google_token_response):
    """Edge: id_token is not a valid JWT — should reject."""
    broken = {**mock_google_token_response, "id_token": "not.a.jwt"}
    respx.post("https://oauth2.googleapis.com/token").mock(
        return_value=Response(200, json=broken)
    )
    response = client.get(
        "/v1/auth/callback",
        params={"code": "c", "state": "s"},
    )
    assert response.status_code in (400, 401)


def test_excessive_state_length_rejected():
    """Edge: state param with abusive length — possible DoS vector."""
    huge_state = "x" * 10000
    response = client.get(
        "/v1/auth/callback",
        params={"code": "c", "state": huge_state},
    )
    assert response.status_code in (400, 403, 413, 422)

